In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("data/train.csv")
test_df = pd.read_csv("data/test.csv")

In [4]:
df.head()

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,...,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,...,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,...,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,...,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,...,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 21 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       630000 non-null  int64
 1   Soil_Type                630000 non-null  object
 2   Soil_pH                  630000 non-null  float64
 3   Soil_Moisture            630000 non-null  float64
 4   Organic_Carbon           630000 non-null  float64
 5   Electrical_Conductivity  630000 non-null  float64
 6   Temperature_C            630000 non-null  float64
 7   Humidity                 630000 non-null  float64
 8   Rainfall_mm              630000 non-null  float64
 9   Sunlight_Hours           630000 non-null  float64
 10  Wind_Speed_kmh           630000 non-null  float64
 11  Crop_Type                630000 non-null  object
 12  Crop_Growth_Stage        630000 non-null  object
 13  Season                   630000 non-null  object
 14  Irrigation_Type          630000 non-null  object
 15  Water_Source             630000 non-null  object
 16  Field_Area_hectare       630000 non-null  float64
 17  Mulching_Used            630000 non-null  object
 18  Previous_Irrigation_mm   630000 non-null  float64
 19  Region                   630000 non-null  object
 20  Irrigation_Need          630000 non-null  object
dtypes: float64(11), int64(1), object(9)
memory usage: 100.9+ MB

In [6]:
df.describe()

,id,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,Previous_Irrigation_mm
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,6.482497,37.304482,0.922858,1.744605,26.998166,61.563180,1462.207566,7.513382,10.375394,7.517745,62.318177
std,181865.479132,0.922504,16.377082,0.365808,0.952321,8.623621,19.708152,612.989738,1.999322,5.689458,4.218124,34.246939
min,0.000000,4.800000,8.000000,0.300000,0.100000,12.000000,25.000000,0.380000,4.000000,0.500000,0.300000,0.020000
25%,157499.750000,5.690000,23.340000,0.610000,0.930000,19.517500,45.390000,954.570000,5.760000,5.280000,3.880000,33.140000
50%,314999.500000,6.440000,37.750000,0.910000,1.740000,26.960000,61.650000,1467.160000,7.580000,10.480000,7.380000,61.150000
75%,472499.250000,7.270000,51.270000,1.220000,2.580000,34.540000,79.120000,2054.280000,9.250000,15.430000,11.140000,92.690000
max,629999.000000,8.200000,64.990000,1.600000,3.500000,42.000000,94.990000,2499.690000,11.000000,20.000000,15.000000,119.990000

In [7]:
for obj_col in  df.select_dtypes(include='object'):
    print(obj_col, " - ", df[obj_col].unique())

Soil_Type  -  ['Loamy' 'Clay' 'Sandy' 'Silt']
Crop_Type  -  ['Sugarcane' 'Wheat' 'Rice' 'Potato' 'Cotton' 'Maize']
Crop_Growth_Stage  -  ['Sowing' 'Vegetative' 'Flowering' 'Harvest']
Season  -  ['Zaid' 'Kharif' 'Rabi']
Irrigation_Type  -  ['Drip' 'Rainfed' 'Sprinkler' 'Canal']
Water_Source  -  ['Rainwater' 'River' 'Reservoir' 'Groundwater']
Mulching_Used  -  ['No' 'Yes']
Region  -  ['East' 'South' 'North' 'West' 'Central']
Irrigation_Need  -  ['Low' 'Medium' 'High']

In [8]:
df1 = df.drop(["id", "Irrigation_Need"], axis=1)

In [9]:
obj_cols = df1.select_dtypes(include='object').columns
obj_cols

Index(['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Season',
       'Irrigation_Type', 'Water_Source', 'Mulching_Used', 'Region'],
      dtype='object')

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [11]:
col_transformer = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(drop='first', sparse_output=False), obj_cols)
    ],
    remainder='passthrough'
)

In [12]:
df1_transformed = col_transformer.fit_transform(df1)

In [13]:
new_cols = col_transformer.get_feature_names_out()
new_cols

array(['onehot__Soil_Type_Loamy', 'onehot__Soil_Type_Sandy',
       'onehot__Soil_Type_Silt', 'onehot__Crop_Type_Maize',
       'onehot__Crop_Type_Potato', 'onehot__Crop_Type_Rice',
       'onehot__Crop_Type_Sugarcane', 'onehot__Crop_Type_Wheat',
       'onehot__Crop_Growth_Stage_Harvest',
       'onehot__Crop_Growth_Stage_Sowing',
       'onehot__Crop_Growth_Stage_Vegetative', 'onehot__Season_Rabi',
       'onehot__Season_Zaid', 'onehot__Irrigation_Type_Drip',
       'onehot__Irrigation_Type_Rainfed',
       'onehot__Irrigation_Type_Sprinkler',
       'onehot__Water_Source_Rainwater', 'onehot__Water_Source_Reservoir',
       'onehot__Water_Source_River', 'onehot__Mulching_Used_Yes',
       'onehot__Region_East', 'onehot__Region_North',
       'onehot__Region_South', 'onehot__Region_West',
       'remainder__Soil_pH', 'remainder__Soil_Moisture',
       'remainder__Organic_Carbon', 'remainder__Electrical_Conductivity',
       'remainder__Temperature_C', 'remainder__Humidity',
       'remainder__Rainfall_mm', 'remainder__Sunlight_Hours',
       'remainder__Wind_Speed_kmh', 'remainder__Field_Area_hectare',
       'remainder__Previous_Irrigation_mm'], dtype=object)

In [14]:
df2 = pd.DataFrame(df1_transformed, columns=new_cols)

In [15]:
assert(len(df2.select_dtypes(include='object').columns) == 0)

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

In [17]:
models = {
    "logistic_regression": LogisticRegression(),
    "decision_tree": DecisionTreeClassifier(),
    "xgboost": XGBClassifier(),
    "catboost": CatBoostClassifier(verbose=0)
}

In [18]:
y = df['Irrigation_Need']

In [19]:
mapping = {'Low': 0, 'Medium': 1, 'High': 2}

y_train = y.map(mapping)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(df2, y_train, test_size=0.2, random_state=42)

In [21]:
from sklearn.metrics import balanced_accuracy_score

In [22]:
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(name, " - ", model.score(X_test, y_test))
    print("balanced_accuracy_score =", balanced_accuracy_score(y_test, y_pred), '\n')

/home/aum/anaconda3/envs/ml/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

logistic_regression  -  0.7256666666666667
balanced_accuracy_score = 0.4856260599261195

decision_tree  -  0.9703253968253969
balanced_accuracy_score = 0.9450349286963527

xgboost  -  0.9844603174603175
balanced_accuracy_score = 0.9597870040665902

catboost  -  0.9851349206349206
balanced_accuracy_score = 0.9599202768741226

In [23]:
test_df1 = test_df.drop('id', axis=1)

In [24]:
test_transformed = col_transformer.transform(test_df1)

In [25]:
test_transformed_df = pd.DataFrame(
    test_transformed,
    columns=col_transformer.get_feature_names_out(),
    index=test_df1.index
)

In [31]:
pred = models['catboost'].predict(test_transformed_df)

In [32]:
reverse_mapping = {v: k for k, v in mapping.items()}

In [40]:
y_pred_labels = pd.Series(pred.ravel()).map(reverse_mapping)

In [41]:
sub_df = pd.DataFrame({
    "id": test_df["id"],
    "Irrigation_Need": y_pred_labels
})

In [43]:
sub_df.to_csv("submission.csv", index=False)